services:
  xvfb:
    build: ./xvfb
    hostname: xvfb
    container_name: eewrenderer${VARIANT:-}__xvfb
    restart: unless-stopped

    command: Xvfb :1 -listen tcp -ac -screen 0 1024x768x24

    deploy:
      replicas: ${XVFB_REPLICAS:-0}
      resources:
        limits:
          memory: 128m

    networks:
      - default

  eewrenderer:
    image: ghcr.io/eewbot/eew-renderer:master
    hostname: eewrenderer
    container_name: eewrenderer${VARIANT:-}__eewrenderer
    restart: unless-stopped

    environment:
      LISTEN: 0.0.0.0:3000
      DISPLAY: ${X_DISPLAY}
      ALLOW_DEMO: ${ALLOW_DEMO}
      HMAC_KEY: ${HMAC_KEY}
      INSTANCE_NAME: ${INSTANCE_NAME}

    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix

    command: /usr/bin/eew-renderer

    deploy:
      resources:
        limits:
          memory: 256m

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2025.4.0
    hostname: cloudflared
    container_name: eewrenderer${VARIANT:-}__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      default:

networks:
  default:
    name: eewrenderer${VARIANT:-}__default
