services:
  eewrenderer:
    image: ghcr.io/eewbot/eew-renderer:v0.1.1
    hostname: eewrenderer
    container_name: eewrenderer${VARIANT:-}__eewrenderer
    restart: unless-stopped

    environment:
      LISTEN: 0.0.0.0:3000
      DISPLAY: ${DISPLAY}
      ALLOW_DEMO: ${ALLOW_DEMO}
      HMAC_KEY: ${HMAC_KEY}
      INSTANCE_NAME: ${INSTANCE_NAME}
      MINIMUM_RESPONSE_INTERVAL: ${MINIMUM_RESPONSE_INTERVAL}

    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix

    command: /usr/bin/eew-renderer

    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2025.4.2
    hostname: cloudflared
    container_name: eewrenderer${VARIANT:-}__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: eewrenderer${VARIANT:-}__default
